ERP.UI/Areas/Accounts/Controllers/LedgerController.cs
using ERP.Models.Accounts;
using ERP.Models.Accounts.Enums;
using ERP.Models.Admin;
using ERP.Models.Common;
using ERP.Models.Extension;
using ERP.Models.Helpers;
using ERP.Services.Accounts.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ERP.UI.Areas.Accounts.Controllers
{
    [Area("Accounts")]
    public class LedgerController : Controller
    {
        private readonly ILedger _ledger;
        private readonly ILedgerAddress _ledgerAddress;
        private readonly ILedgerFinancialYearBalance _ledgerFinancialYearBalance;

        public LedgerController(
            ILedger ledger,
            ILedgerAddress ledgerAddress,
            ILedgerFinancialYearBalance ledgerFinancialYearBalance
            )
        {
            this._ledger = ledger;
            this._ledgerAddress = ledgerAddress;
            this._ledgerFinancialYearBalance = ledgerFinancialYearBalance;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.ParentGroupList = await _ledger.GetGroupSelectList(0);

            return await Task.Run(() =>
            {
                return View();
            });
        }

        [HttpPost]
        public async Task<IActionResult> GetLedgerList(DataTableAjaxPostModel dataTableAjaxPostModel, string searchFilter)
        {
            // deserilize string search filter.
            SearchFilterLedgerModel searchFilterModel = JsonConvert.DeserializeObject<SearchFilterLedgerModel>(searchFilter);
            // get data.
            DataTableResultModel<LedgerModel> resultModel = await _ledger.GetLedgerList(dataTableAjaxPostModel, searchFilterModel);

            return await Task.Run(() =>
            {
                return Json(new
                {
                    dataTableAjaxPostModel.draw,
                    recordsTotal = resultModel.TotalResultCount,
                    recordsFiltered = resultModel.TotalResultCount,
                    data = resultModel.ResultList
                });
            });
        }

        public async Task<IActionResult> AddLedgerMaster()
        {
            ViewBag.ParentGroupList = await _ledger.GetGroupSelectList(0);

            LedgerModel ledgerModel = new LedgerModel();

            // generate no.
            GenerateNoModel generateNoModel = await _ledger.GenerateLedgerCode();

            ledgerModel.LedgerCode = generateNoModel.VoucherNo;

            return await Task.Run(() =>
            {
                return PartialView("_AddLedgerMaster", ledgerModel);
            });
        }

        public async Task<IActionResult> EditLedgerMaster(int ledgerId)
        {
            ViewBag.ParentGroupList = await _ledger.GetGroupSelectList(0);

            LedgerModel ledgerModel = await _ledger.GetLedgerById(ledgerId);

            return await Task.Run(() =>
            {
                return PartialView("_AddLedgerMaster", ledgerModel);
            });
        }

        [HttpPost]
        public async Task<JsonResult> SaveLedgerMaster(LedgerModel ledgerModel)
        {
            JsonData<JsonStatus> data = new JsonData<JsonStatus>(new JsonStatus());

            if (ModelState.IsValid)
            {
                //To check number of levels

                if (ledgerModel.IsGroup==true)
                {
                    LedgerModel ledgerModel_Parent = await _ledger.GetLedgerById((int)ledgerModel.ParentGroupId);

                    if (ledgerModel_Parent.IsMasterGroup==false)
                    {
                        data.Result.Status = false;
                        data.Result.Data = ledgerModel.LedgerId;
                        data.Result.Message = "You can not add/update this group. Selected group's parent group is not master group.";

                        return Json(data);
                    }
                }


                if (ledgerModel.LedgerId > 0)
                {
                    if (ledgerModel.IsGroup==false)
                    {
                        DataTableResultModel<LedgerModel> resultModel = await _ledger.GetLedgerListByParentGroupId(ledgerModel.LedgerId);

                        if (resultModel.TotalResultCount!=0)
                        {
                            data.Result.Status = false;
                            data.Result.Data = ledgerModel.LedgerId;
                            data.Result.Message = "You can not remove 'Is Group'. Group is referred as parent group in other Group/Ledger";

                            return Json(data);
                        }

                    }

                    // update record.
                    if (true == await _ledger.UpdateLedger(ledgerModel))
                    {
                        data.Result.Status = true;
                        data.Result.Data = ledgerModel.LedgerId;
                    }
                }
                else
                {
                    // generate no.
                    GenerateNoModel generateNoModel = await _ledger.GenerateLedgerCode();

                    ledgerModel.LedgerCode = generateNoModel.VoucherNo;
                    ledgerModel.MaxNo = generateNoModel.MaxNo;

                    ledgerModel.LedgerId = await _ledger.CreateLedger(ledgerModel);

                    // add new record.
                    if (ledgerModel.LedgerId > 0)
                    {
                        data.Result.Status = true;
                        data.Result.Data = ledgerModel.LedgerId;
                    }
                }
            }

            return Json(data);
        }

        public async Task<IActionResult> ManageLedger(int ledgerId)
        {
            ViewBag.LedgerId = ledgerId;

            LedgerModel ledgerModel = await _ledger.GetLedgerById(ledgerId);

            ViewBag.IsAddressVisible = false;
            ViewBag.IsEditVisible =false;
            ViewBag.IsUpdateBalanceVisible =false;

            if (ledgerModel.ParentGroupId == (int)LedgerName.SundryDebtor || ledgerModel.ParentGroupId == (int)LedgerName.SundryCreditor)
            {
                ViewBag.IsAddressVisible = true;
            }

            if (ledgerModel.IsMasterGroup == false)
            {
                ViewBag.IsEditVisible = true;
            }

            if (ledgerModel.IsGroup == false)
            {
                ViewBag.IsUpdateBalanceVisible = true;
            }

            return await Task.Run(() =>
            {
                return View();
            });
        }

        public async Task<IActionResult> ViewLedgerMaster(int ledgerId)
        {
            LedgerModel ledgerModel = await _ledger.GetLedgerById(ledgerId);

            if (ledgerModel==null)
            {
                return NotFound("Record not exists");
            }

            UserSessionModel userSession = SessionExtension.GetComplexData<UserSessionModel>(HttpContext.Session, "UserSession");

            LedgerFinancialYearBalanceModel ledgerFinancialYearBalanceModel = await _ledgerFinancialYearBalance.GetLedgerFinancialYearBalance(ledgerId, userSession.CompanyId, userSession.FinancialYearId);

            if (ledgerFinancialYearBalanceModel != null)
            {
                ledgerModel.CreditAmountOpBal=ledgerFinancialYearBalanceModel.CreditAmount;
                ledgerModel.DebitAmountOpBal=ledgerFinancialYearBalanceModel.DebitAmount;
            }


            return await Task.Run(() =>
            {
                return PartialView("_ViewLedgerMaster", ledgerModel);
            });
        }

        [HttpPost]
        public async Task<JsonResult> DeleteLedgerMaster(int ledgerId)
        {
            JsonData<JsonStatus> data = new JsonData<JsonStatus>(new JsonStatus());

            if (true == await _ledger.DeleteLedger(ledgerId))
            {
                data.Result.Status = true;
            }

            return Json(data); // returns.
        }

        public async Task<IActionResult> EditLedgerBalance(int ledgerId)
        {
            UserSessionModel userSession = SessionExtension.GetComplexData<UserSessionModel>(HttpContext.Session, "UserSession");

            LedgerFinancialYearBalanceModel ledgerFinancialYearBalanceModel = await _ledgerFinancialYearBalance.GetLedgerFinancialYearBalance(ledgerId, userSession.CompanyId, userSession.FinancialYearId);

            if (ledgerFinancialYearBalanceModel == null)
            {
                ledgerFinancialYearBalanceModel=new LedgerFinancialYearBalanceModel();

                ledgerFinancialYearBalanceModel.CompanyId=userSession.CompanyId;
                ledgerFinancialYearBalanceModel.FinancialYearId=userSession.FinancialYearId;
            }

            return await Task.Run(() =>
            {
                return PartialView("_UpdateLedgerBalance", ledgerFinancialYearBalanceModel);
            });
        }

        [HttpPost]
        public async Task<JsonResult> SaveUpdateLedgerBalance(LedgerFinancialYearBalanceModel ledgerFinancialYearBalanceModel)
        {
            JsonData<JsonStatus> data = new JsonData<JsonStatus>(new JsonStatus());

            if (ModelState.IsValid)
            {
                if (ledgerFinancialYearBalanceModel.LedgerBalanceId > 0)
                {
                    // update record.
                    if (true == await _ledgerFinancialYearBalance.UpdateLedgerFinancialYearBalance(ledgerFinancialYearBalanceModel))
                    {
                        data.Result.Status = true;
                        data.Result.Data = ledgerFinancialYearBalanceModel.LedgerId;
                    }
                }
                else
                {
                    ledgerFinancialYearBalanceModel.LedgerBalanceId = await _ledgerFinancialYearBalance.CreateLedgerFinancialYearBalance(ledgerFinancialYearBalanceModel);

                    // add new record.

ERP.UI/Areas/Accounts/Views/Ledger/Index.cshtml
@model SearchFilterLedgerModel

@{ ViewBag.Title = "Ledger List"; }

<section class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <h5>@ViewBag.Title</h5>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body p-2" id="searchFilterCriteria">
                        <div class="row">
                            <div class="col-6 col-sm-2">
                                <div class="form-group-sm">
                                    @Html.LabelFor(model => model.LedgerName, new { @class = "" })
                                    @Html.TextBoxFor(model => model.LedgerName, new { @class = "form-control form-control-sm" })
                                </div>
                            </div>
                            <div class="col-6 col-sm-2">
                                <div class="form-group-sm">
                                    @Html.LabelFor(model => model.FromDate)
                                    @Html.TextBoxFor(model => model.FromDate, new { @class = "form-control form-control-sm", autocomplete = "off", @placeholder = "DD/MMM/YYYY" })
                                </div>
                            </div>
                            <div class="col-6 col-sm-2">
                                <div class="form-group-sm">
                                    @Html.LabelFor(model => model.ToDate)
                                    @Html.TextBoxFor(model => model.ToDate, new { @class = "form-control form-control-sm", autocomplete = "off", @placeholder = "DD/MMM/YYYY" })
                                </div>
                            </div>
                            <div class="col-6 col-sm-2">
                                <div class="form-group-sm">
                                    @Html.LabelFor(model => model.ParentGroupId, new { @class = "" })
                                    @Html.DropDownListFor(model => model.ParentGroupId, new SelectList(ViewBag.ParentGroupList, "Value", "DisplayText"), "Select", new { @class = "form-control form-control-sm" })
                                </div>
                            </div>
                            <div class="col-6 col-sm-2">
                                <div class="form-group-sm">
                                    @Html.LabelFor(model => model.IsGroup, new { @class = "" })
                                    <div class="col-1">
                                        @Html.CheckBoxFor(model => model.IsGroup, new { @class = "" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 pt-2 text-right">
                                <button class="btn btn-primary" type="button" onclick="javascript: fnSearchLedger();">
                                    <i class="fas fa-search"></i> Search
                                </button>
                                <button class="btn btn-secondary" type="button" onclick="javascript: fnResetSearch();">
                                    <i class="fas fa-undo"></i> Reset
                                </button>
                                <button class="btn btn-primary" type="button" onclick="javascript: fnAddLedger();">
                                    <i class="fas fa-plus"></i> New
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @*<div class="col-sm-12 table-responsive">*@
                <table id="ledgerGrid" class="table table-bordered table-striped w-100">
                    <thead>
                        <tr class="table-header">
                            <th class="no-sort"></th>
                            <th>LedgerId</th>
                            <th>Ledger Code</th>
                            <th>Ledger Name</th>
                            <th>Parent Group</th>
                            <th>Prepared By</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</section>

<div id="modal-ledger" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="true"></div>

<script type="text/javascript">
    const FROM_PATTERN = 'YYYY-MM-DD HH:mm:ss.SSS';
    const TO_PATTERN = 'DD/MM/YYYY HH:mm';
    $(document).ready(function () {
        $("#ledgerGrid").DataTable({
            "pageLength": 25,
            "lengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
            "processing": true,
            "scrollX": true,
            "dom": "<'row'<'col-sm-12'tr>>" +
                "<'row'<'col-sm-4'i><'col-sm-4 text-center'l><'col-sm-4'p>>",
            //'lrtip',
            "serverSide": true,
            "ajax": {
                "url": "@Url.Action("GetLedgerList", "Ledger")",
                "type": "POST",
                "datatype": "json",
                "data": {
                    searchFilter: function () {
                        var searchFilterModel = {
                            LedgerName: $('#LedgerName').val(),
                            ParentGroupId: $('#ParentGroupId').val(),
                            FromDate: $('#FromDate').val(),
                            ToDate: $('#ToDate').val(),
                            IsGroup: $('#IsGroup').is(":checked"),
                        };

                        console.log(searchFilterModel);

                        return JSON.stringify(searchFilterModel);
                    }
                },
            },
            "columns": [
                {
                    "orderable": false,
                    "render": function (data, type, full, meta) {
                        return '<div class="action_button">' +
                            '<button type="button" class="border-0 rounded-0 text-success" title="Edit" onclick="javascript: fnEditLedgerMaster(' + full.LedgerId + ')"><i class="far fa-edit"></i></button>' +
                           /* '<button type="button" class="border-0 rounded-0 text-danger" title="Delete" data-toggle="modal" onclick="javascript: fnDeleteLedgerMaster(this, ' + full.LedgerId + ')"><i class="fa fa-trash-alt"></i></button>' +*/
                            '</div>';
                    }
                },
                { "data": "LedgerId", "name": "LedgerId", "visible": false },
                { "data": "LedgerCode", "name": "Ledger Code" },
                { "data": "LedgerName", "name": "Ledger Name" },
                { "data": "ParentGroupName", "name": "Parent Group Name" },
                { "data": "PreparedByName", "name": "Prepared By Name" }
            ],
        });

        $('#FromDate').datetimepicker({
            format: 'DD/MMM/YYYY',
            useCurrent: false,
            defaultDate: false, // setValue:''
            widgetPositioning: {
                horizontal: 'left',
                vertical: 'bottom'
            }

        });

        $('#ToDate').datetimepicker({
            format: 'DD/MMM/YYYY',
            useCurrent: false,
            defaultDate: false, // setValue:''
            widgetPositioning: {
                horizontal: 'left',
                vertical: 'bottom'
            }
        });
    });

    // edit ledger.
    function fnEditLedgerMaster(ledgerId) {
        window.location.href = '@Url.Action("ManageLedger", "Ledger")?ledgerId=' + ledgerId;
    }

    // delete ledger.
    function fnDeleteLedgerMaster(ledgerId) {

    }

    // search data.
    function fnSearchLedger() {
        $("#ledgerGrid").DataTable().ajax.reload();
    }

    // reset filter.
    function fnResetSearch() {
        $('#searchFilterCriteria :input[type=text]').each(function (index) {
            $(this).val('');
        });
        $('#searchFilterCriteria select').each(function (index) {
            $(this).val('');
        });
        $('#searchFilterCriteria :input[type=checkbox]').each(function (index) {
            $(this).is(":checked")==false;
        });

        $("#ledgerGrid").DataTable().ajax.reload();
    }

    // new button click.
    function fnAddLedger() {
        AjaxCommunication.CreateRequest(this.window, 'Get', '@Url.Action("AddLedgerMaster", "Ledger")', 'html', '',
        function (data) {
            $('#modal-ledger').empty();
            $('#modal-ledger').html(data).modal('show');
            return false;
        }, 
        function (XMLHttpRequest, textStatus, errorThrown) {
            errorCallback(XMLHttpRequest, textStatus, errorThrown);
        }, true, null, false);
    }

</script>
@*@{ await Html.RenderPartialAsync("_ConfirmDeleteLedgerMaster"); }*@

ERP.UI/Areas/Accounts/Views/Ledger/_AddLedgerMaster.cshtml
@model LedgerModel

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            @if (Model.LedgerId > 0)
            {
<h5 class="modal-title">Edit Ledger</h5> }
else
{
<h5 class="modal-title">Add Ledger</h5>}
            <button type="button" class="close btn-default" data-dismiss="modal" aria-label="Close">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <form id="frmLedgerMaster" class="width100" method="post"
              asp-action="SaveLedgerMaster" asp-controller="Ledger" asp-area="Accounts"
              data-ajax-begin="return BeginLedgerMaster();" data-ajax-success="SuccessLedgerMaster"
              data-ajax="true" data-ajax-method="post">

            <div class="modal-body">
                @Html.HiddenFor(model => model.LedgerId)

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.LedgerCode, new { @class = "required" })
                            @Html.TextBoxFor(model => model.LedgerCode, new { @class = "form-control form-control-sm", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.LedgerCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.LedgerName, new { @class = "required" })
                            @Html.TextBoxFor(model => model.LedgerName, new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.LedgerName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ParentGroupId)
                            @Html.DropDownListFor(model => model.ParentGroupId, new SelectList(ViewBag.ParentGroupList, "Value", "DisplayText"), "Select", new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.ParentGroupId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TaxRegisteredNo)
                            @Html.TextBoxFor(model => model.TaxRegisteredNo, new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.TaxRegisteredNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.IsGroup, new { @class = "" })
                            <div class="col-1">
                                @Html.CheckBoxFor(model => model.IsGroup, new { @class = "form-control form-control-sm" })
                            </div>
                            @Html.ValidationMessageFor(model => model.IsGroup, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control form-control-sm col-sm-12" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
               
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" title="Back"><i class="fas fa-arrow-left"></i> Back</button>
                <button type="submit" class="btn btn-primary" title="Save"><i class="fas fa-save"></i> Save</button>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

    }); //document ready

    // begin form
    function BeginLedgerMaster() {
        var form = $("#frmLedgerMaster");
        $(form).removeData("validator").removeData("unobtrusiveValidation");
        $.validator.unobtrusive.parse($(form));
        var validator = $(form).validate();
        var isModelValid = $(form).valid();
        if (false == isModelValid) {
            validator.focusInvalid();
            return false;
        }
    }
    // success form
    function SuccessLedgerMaster(data) {

        if (data.Result.Status) {
            $('#modal-ledger').modal('hide');
            fnSuccessNotify('Record saved sucessfully.');

             var tabUrl = '@Url.Action("ManageLedger", "Ledger")?ledgerId=' + data.Result.Data;
            window.location.href = tabUrl;
        }
        else {
            fnDangerNotify(data.Result.Message);
            return false;
        }
    }
</script>

<style type="text/css">
    .modal-body {
        height: 250px;
        overflow-y: auto;
    }

    @@media (min-height: 500px) {
        .modal-body {
            height: 400px;
        }
    }

    @@media (min-height: 800px) {
        .modal-body {
            height: 600px;
        }
    }
</style>

ERP.UI/Areas/Accounts/Views/Ledger/_UpdateLedgerBalance.cshtml
@model LedgerFinancialYearBalanceModel

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Update Ledger Balance</h5> 
            <button type="button" class="close btn-default" data-dismiss="modal" aria-label="Close">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <form id="frmUpdateLedgerBalance" class="width100" method="post"
              asp-action="SaveUpdateLedgerBalance" asp-controller="Ledger" asp-area="Accounts"
              data-ajax-begin="return BeginUpdateLedgerBalance();" data-ajax-success="SuccessUpdateLedgerBalance"
              data-ajax="true" data-ajax-method="post">

            <div class="modal-body">
                @Html.HiddenFor(model => model.LedgerBalanceId)
                @Html.HiddenFor(model => model.LedgerId)
                @Html.HiddenFor(model => model.CompanyId)
                @Html.HiddenFor(model => model.FinancialYearId)

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CreditAmount)
                            @Html.TextBoxFor(model => model.CreditAmount, new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.CreditAmount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.DebitAmount)
                            @Html.TextBoxFor(model => model.DebitAmount, new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.DebitAmount, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" title="Back"><i class="fas fa-arrow-left"></i> Back</button>
                <button type="submit" class="btn btn-primary" title="Save"><i class="fas fa-save"></i> Save</button>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

    }); //document ready

    // begin form
    function BeginUpdateLedgerBalance() {
        var form = $("#frmUpdateLedgerBalance");
        $(form).removeData("validator").removeData("unobtrusiveValidation");
        $.validator.unobtrusive.parse($(form));
        var validator = $(form).validate();
        var isModelValid = $(form).valid();
        if (false == isModelValid) {
            validator.focusInvalid();
            return false;
        }

        var isValid = true;

        if (parseFloat($("#CreditAmount").val()) != 0 && parseFloat($("#DebitAmount").val()) != 0) {
            alert("You can not enter both credit amount & debit amount. Please enter either credit amount or debit amount.");
            $("#CreditAmount").focus();
            isValid = false;
            return false;
        }

        if (isValid == false) {
            return false;
        }
    }
    // success form
    function SuccessUpdateLedgerBalance(data) {

        if (data.Result.Status) {
            $('#modal-ledger').modal('hide');
            fnSuccessNotify('Record saved sucessfully.');

             var tabUrl = '@Url.Action("ManageLedger", "Ledger")?ledgerId=' + data.Result.Data;
            window.location.href = tabUrl;
        }
        else {
            fnDangerNotify('Error occured while processing request.');
            return false;
        }
    }
</script>

<style type="text/css">
    .modal-body {
        height: 250px;
        overflow-y: auto;
    }

    @@media (min-height: 500px) {
        .modal-body {
            height: 400px;
        }
    }

    @@media (min-height: 800px) {
        .modal-body {
            height: 600px;
        }
    }
</style>