ERP.UI/Areas/Accounts/Controllers/PaymentRegisterController.cs
using ERP.Models.Accounts;
using ERP.Models.Admin;
using ERP.Models.Common;
using ERP.Models.Extension;
using ERP.Services.Accounts.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace ERP.UI.Areas.Accounts.Controllers
{
    [Area("Accounts")]
    public class PaymentRegisterController : Controller
    {
        private readonly IPaymentRegister _paymentRegister;
        private readonly IFinancialYear _financialYear;
        private readonly ILedger _ledger;

        public PaymentRegisterController(ILedger ledger, IFinancialYear financialYear, IPaymentRegister paymentRegister)
        {
            this._paymentRegister = paymentRegister;
            this._ledger = ledger;
            this._financialYear = financialYear;
        }

        public async Task<IActionResult> Index()
        {
            return await Task.Run(() =>
            {
                return View();
            });
        }

        public async Task<IActionResult> Search(string searchFilter)
        {
            //ViewBag.LedgerList = await _ledger.GetLedgerSelectList(0, true);

            UserSessionModel userSession = SessionExtension.GetComplexData<UserSessionModel>(HttpContext.Session, "UserSession");

            FinancialYearModel financialYearModel = await _financialYear.GetFinancialYearById(userSession.FinancialYearId);

            SearchFilterPaymentRegisterModel searchFilterPaymentRegisterModel = new SearchFilterPaymentRegisterModel();

            if (searchFilter==null)
            {
                searchFilterPaymentRegisterModel.FromDate = financialYearModel.FromDate;
                searchFilterPaymentRegisterModel.ToDate = financialYearModel.ToDate;
            }
            else
            {
                // deserilize string search filter.

                SearchFilterPaymentRegisterModel searchFilterModel = JsonConvert.DeserializeObject<SearchFilterPaymentRegisterModel>(searchFilter);

                //searchFilterPaymentRegisterModel.LedgerId = searchFilterModel.LedgerId;
                searchFilterPaymentRegisterModel.FromDate = searchFilterModel.FromDate;
                searchFilterPaymentRegisterModel.ToDate = searchFilterModel.ToDate;
            }


            return await Task.Run(() =>
            {
                return PartialView("_Search", searchFilterPaymentRegisterModel);
            });
        }

        public async Task<IActionResult> Detail()
        {
            return await Task.Run(() =>
            {
                return PartialView("_Detail");
            });
        }

        [HttpPost]
        public async Task<IActionResult> GetTransactionList(string searchFilter)
        {
            UserSessionModel userSession = SessionExtension.GetComplexData<UserSessionModel>(HttpContext.Session, "UserSession");

            FinancialYearModel financialYearModel = await _financialYear.GetFinancialYearById(userSession.FinancialYearId);

            // deserilize string search filter.
            SearchFilterPaymentRegisterModel searchFilterModel = JsonConvert.DeserializeObject<SearchFilterPaymentRegisterModel>(searchFilter);

            searchFilterModel.CompanyId=userSession.CompanyId;
            searchFilterModel.FinancialYearId=userSession.FinancialYearId;

            // get data.
            DataTableResultModel<PaymentRegisterModel> resultModel = await _paymentRegister.GetReport(searchFilterModel,
                                                                                            financialYearModel.FromDate, financialYearModel.ToDate);

            return await Task.Run(() =>
            {
                return Json(new
                {
                    draw = "1",
                    recordsTotal = resultModel.TotalResultCount,
                    data = resultModel.ResultList
                });
            });
        }

    }
}

ERP.UI/Areas/Accounts/Views/PaymentRegister/Index.cshtml
@{ ViewBag.Title = "Payment Register Report"; }

<section class="content-header p-2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-10">
                <div class="row">
                    <div id="title" class="col-sm-3 h5">@ViewBag.Title</div>
                    <div id="filterDetails" class="col-sm-9 h6"></div> @*to show party name*@ 
                </div>
            </div>
            <div class="col-sm-2">
                <div id="buttons" class="float-right">
                    <button type="button" class="btn btn-secondary" id="Back" title="Back" hidden onclick="javascript: fnBackToIndex();">
                        <i class="fas fa-arrow-left"></i> Back
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="content p-0">
    <div class="container-fluid">
        <input type="hidden" id="SearchFilterModel" />
        <div id="rptDetails"></div>
    </div>
</section>

<script type="text/javascript">

    $(document).ready(function () {
        fnBackToIndex();
    });

    function fnBackToIndex() {

        var tabUrl = null;

        tabUrl = '@Url.Action("Search", "PaymentRegister")' + '?searchFilter=' + $("#SearchFilterModel").val();;

        $('#rptDetails').empty();
        $('#rptDetails').load(tabUrl);
    }

    //// search data.
    function fnSearchData(searchFilterModel) {
        //fnBindDataTable();

       var tabUrl = null;

        $("#SearchFilterModel").val(searchFilterModel);

        tabUrl = '@Url.Action("Detail", "PaymentRegister")' + '?searchFilter=' + $("#SearchFilterModel").val();

        $("#Back").removeAttr('hidden');

        $('#rptDetails').empty();
        $('#rptDetails').load(tabUrl);
    }


</script>

ERP.UI/Areas/Accounts/Views/PaymentRegister/_Detail.cshtml
<div class="row">
    <div class="col-sm-12">
        <table id="reportGrid" class="table table-bordered table-striped w-100">
            @*<thead>
                    <tr class="table-header">
                        <th>Voucher Type</th>
                        <th>Voucher No</th>
                        <th>Voucher Date</th>
                    </tr>
                </thead>*@
        </table>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {
        fnBindDataTable();
    });

    // search data.
    function fnBindDataTable() {

        var searchFilter = $("#SearchFilterModel").val();

        var jsonFilter = JSON.parse(searchFilter);

        var fileName = "Payment Register";

        var reportTitle = "Payment Register " + "(From - " + jsonFilter.FromDate + " To - " + jsonFilter.ToDate + ")" ;

        $("#reportGrid").DataTable({
            "destroy": true,
            "pageLength": 25,
            "paging": false,
            "searching": false,
            "ordering": false,
            "info": false,
            "scrollX": true,
            //"dom": "<'row'<'col-sm-12'tr>>" +
            //    "<'row'<'col-sm-4'i><'col-sm-4 text-center'l><'col-sm-4'p>>",
            //'lrtip',
            /*"serverSide": true,*/
            "dom":"Bfrtip",
            buttons: [
                {
                    extend: 'excelHtml5',
                    text: '<i class="fas fa-file-excel"></i> Excel',
                    titleAttr: 'Excel',
                    className: 'btn btn-default',
                    orientation: 'landscape',
                    pageSize: 'A4',
                    filename: fileName,
                    title: reportTitle
                },
                {
                    extend: 'pdfHtml5',
                    text: '<i class="fas fa-file-pdf"></i> PDF',
                    titleAttr: 'PDF',
                    className: 'btn btn-default',
                    orientation: 'landscape',
                    pageSize: 'A4',
                    filename: fileName,
                    title: reportTitle
                }
            ],
            "ajax": {
                "url": "@Url.Action("GetTransactionList", "PaymentRegister")",
                "type": "POST",
                "datatype": "json",
                "data": {
                    searchFilter: searchFilter
                },
            },
            "columns": [
                {
                    "data": "DocumentNo", "name": "DocumentNo", "title": "Voucher No", className: "dt-nowrap",
                    "render": function (data, type, full, meta) {
                        if (full.SequenceNo == 1 || full.SequenceNo == 3) {
                            return '<b>' + full.DocumentNo + '</b>';
                        }
                        else {
                            return full.DocumentNo;
                        }
                    }
                },
                {
                    "data": "DocumentDate", "name": "DocumentDate", "title": "Voucher Date",
                    "render": function (dt) {
                        return moment(dt).format("DD/MMM/YYYY");
                    }
                },
                { "data": "ChequeNo", "name": "ChequeNo", "title": "Cheque No" },
                {
                    "data": "ChequeDate", "name": "ChequeDate", "title": "Cheque Date",
                    "render": function (dt) {
                        if (Date.parse(dt)) {
                            return moment(dt).format("DD/MMM/YYYY");
                        }
                        else {
                            return "";
                        }
                    }
                },
                { "data": "BankName", "name": "BankName", "title": "Bank" },
                { "data": "ParticularLedgerName", "name": "ParticularLedgerName", "title": "Particular" },
                { "data": "Narration", "name": "Narration", "title": "Narration" },
                { "data": "InvoiceType", "name": "InvoiceType", "title": "Invoice Type" },
                { "data": "InvoiceNo", "name": "InvoiceNo", "title": "Invoice No" },
                { "data": "CurrencyCode", "name": "CurrencyCode", "title": "Currency" },
                {
                    "data": "ExchangeRate", "name": "ExchangeRate", "title": "Exchange Rate", className: "dt-right dt-nowrap",
                    "render": function (data, type, full, meta) {
                        if (full.SequenceNo == 1 || full.SequenceNo == 3) {
                            return '';
                        }
                        else {
                            return addCommas(full.ExchangeRate);
                        }
                    }
                },
                {
                    "data": "Amount_FC", "name": "Amount_FC", "title": "Amount FC", className: "dt-right dt-nowrap",
                    "render": function (data, type, full, meta) {
                        if (full.SequenceNo == 1 || full.SequenceNo == 3) {
                            return '';
                        }
                        else {
                            return addCommas(full.Amount_FC);
                        }
                    }
                },
                {
                    "data": "Amount", "name": "Amount", "title": "Amount", className: "dt-right dt-nowrap",
                    "render": function (data, type, full, meta) {
                        if (full.SequenceNo == 1 || full.SequenceNo == 3) {
                            return '<b>' + addCommas(full.Amount) + '</b>';
                        }
                        else {
                            return addCommas(full.Amount);
                        }
                    }
                },
            ],
        });


    }

</script>

ERP.UI/Areas/Accounts/Views/PaymentRegister/_Search.cshtml
@model SearchFilterPaymentRegisterModel

<form id="frmPaymentRegister" class="width100" method="post"
              data-ajax-begin="return BeginSearch();" 
              data-ajax="true" data-ajax-method="post"
      >
    <div class="row">
        <div class="col-sm-6">
            <div class="card m-0">
                <div class="card-body p-2" id="searchFilterCriteria">
                    <div class="row">
                        @*<div class="col-6 col-sm-4">
                            <div class="form-group-sm">
                                @Html.LabelFor(model => model.LedgerId, new { @class = "" })
                                @Html.DropDownListFor(model => model.LedgerId, new SelectList(ViewBag.LedgerList, "Value", "DisplayText"), "Select", new { @class = "form-control form-control-sm" })
                                @Html.ValidationMessageFor(model => model.LedgerId, "", new { @class = "text-danger" })
                            </div>
                        </div>*@
                        <div class="col-6 col-sm-4">
                            <div class="form-group-sm">
                                @Html.LabelFor(model => model.FromDate)
                                @Html.TextBoxFor(model => model.FromDate, "{0:dd/MMM/yyyy}", new { @class = "form-control form-control-sm", autocomplete = "off", @placeholder = "DD/MMM/YYYY" })
                                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-6 col-sm-4">
                            <div class="form-group-sm">
                                @Html.LabelFor(model => model.ToDate)
                                @Html.TextBoxFor(model => model.ToDate, "{0:dd/MMM/yyyy}", new { @class = "form-control form-control-sm", autocomplete = "off", @placeholder = "DD/MMM/YYYY" })
                                @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-sm-12 pt-2 text-right">
                            <button type="submit" class="btn btn-primary" title="Search">
                                <i class="fas fa-search"></i> Search
                            </button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" title="Reset" onclick="javascript: fnResetSearch();">
                                <i class="fas fa-undo"></i> Reset
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>

<script type="text/javascript">
    $(document).ready(function () {

        $('#FromDate').datetimepicker({
            format: 'DD/MMM/YYYY',
            useCurrent: false,
            defaultDate: false, // setValue:''
            widgetPositioning: {
                horizontal: 'left',
                vertical: 'bottom'
            }

        });

        $('#ToDate').datetimepicker({
            format: 'DD/MMM/YYYY',
            useCurrent: false,
            defaultDate: false, // setValue:''
            widgetPositioning: {
                horizontal: 'left',
                vertical: 'bottom'
            }
        });

    });


       //// search data.
    function BeginSearch() {
        //fnBindDataTable();

        var form = $("#frmPaymentRegister");
        $(form).removeData("validator").removeData("unobtrusiveValidation");
        $.validator.unobtrusive.parse($(form));
        var validator = $(form).validate();
        var isModelValid = $(form).valid();
        if (false == isModelValid) {
            validator.focusInvalid();
            return false;
        }

        var fromDate = $("#FromDate").val(); //2013-09-5
        var toDate = $("#ToDate").val(); //2013-09-10

        if (Date.parse(fromDate) > Date.parse(toDate)) {
            alert("from date should be less than or equal to date.");
            return false;
        }

        var filterModel = {
            /*LedgerName: $('#LedgerId option:selected').text(),*/
            //LedgerId: $('#LedgerId').val(),
            FromDate: $('#FromDate').val(),
            ToDate: $('#ToDate').val(),
        };

        var searchFilterModel = JSON.stringify(filterModel)

        fnSearchData(searchFilterModel);
    }

    // reset filter.

    function fnResetSearch() {
        $("#SearchFilterModel").val('');

        fnBackToIndex();

        //$('#searchFilterCriteria :input[type=text]').each(function (index) {
        //    $(this).val('');
        //});

        //$('#searchFilterCriteria select').each(function (index) {
        //    $(this).val('');
        //});

        //$("#reportGrid").DataTable().clear().draw();

    }

</script>