ERP.UI/Areas/Accounts/Controllers/CreditNoteTaxDetailController.cs
using ERP.Models.Accounts;
using ERP.Models.Accounts.Enums;
using ERP.Models.Admin;
using ERP.Models.Common;
using ERP.Models.Extension;
using ERP.Models.Helpers;
using ERP.Services.Accounts.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ERP.UI.Areas.Accounts.Controllers
{
    [Area("Accounts")]
    public class CreditNoteTaxDetailController : Controller
    {
        private readonly ICreditNoteDetailTax _creditNoteDetailTax;
        private readonly ILedger _ledger;

        /// <summary>
        /// constractor.
        /// </summary>
        public CreditNoteTaxDetailController(ICreditNoteDetailTax creditNoteDetailTax, ILedger ledger)
        {
            this._creditNoteDetailTax = creditNoteDetailTax;
            this._ledger = ledger;
        }

        /// <summary>
        /// creditnote tax detail.
        /// </summary>
        /// <param name="creditNoteDetId"></param>
        /// <returns></returns>
        public async Task<IActionResult> CreditNoteTaxDetail(int creditNoteDetId)
        {
            ViewBag.CreditNoteDetId = creditNoteDetId;

            return await Task.Run(() =>
            {
                return PartialView("_CreditNoteTaxDetail");
            });
        }

        ///// <summary>
        ///// view creditnote tax detail.
        ///// </summary>
        ///// <param name="creditNoteDetId"></param>
        ///// <returns></returns>
        //public async Task<IActionResult> ViewCreditNoteTaxDetail(int creditNoteDetId)
        //{
        //    ViewBag.CreditNoteDetId = creditNoteDetId;

        //    return await Task.Run(() =>
        //    {
        //        return PartialView("_ViewCreditNoteTaxDetail");
        //    });
        //}

        /// <summary>
        /// get credit note tax detail list.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> GetCreditNoteTaxDetailList(int creditNoteDetId)
        {
            DataTableResultModel<CreditNoteDetailTaxModel> resultModel = await _creditNoteDetailTax.GetCreditNoteDetailTaxByCreditNoteDetailId(creditNoteDetId);

            return await Task.Run(() =>
            {
                return Json(new
                {
                    draw = "1",
                    recordsTotal = resultModel.TotalResultCount,
                    data = resultModel.ResultList
                });
            });
        }

        /// <summary>
        /// add creditnote tax detail.
        /// </summary>
        /// <param name="creditNoteDetId"></param>
        /// <returns></returns>
        public async Task<IActionResult> AddCreditNoteTaxDetail(int creditNoteDetId)
        {
            UserSessionModel userSession = SessionExtension.GetComplexData<UserSessionModel>(HttpContext.Session, "UserSession");

            ViewBag.DiscountTypeList = EnumHelper.GetEnumListFor<DiscountType>();
            ViewBag.TaxAddOrDeductList = EnumHelper.GetEnumListFor<TaxAddOrDeduct>();
            ViewBag.TaxLedgerList = await _ledger.GetLedgerSelectList((int)LedgerName.DutiesAndTaxes, userSession.CompanyId, true);

            CreditNoteDetailTaxModel creditNoteDetailTaxModel = new CreditNoteDetailTaxModel();
            creditNoteDetailTaxModel.CreditNoteDetId = creditNoteDetId;
            creditNoteDetailTaxModel.SrNo = await _creditNoteDetailTax.GenerateSrNo(creditNoteDetId);

            return await Task.Run(() =>
            {
                return PartialView("_AddCreditNoteTaxDetail", creditNoteDetailTaxModel);
            });
        }

        /// <summary>
        /// edit creditnote tax detail.
        /// </summary>
        /// <param name="creditNoteDetTaxId"></param>
        /// <returns></returns>
        public async Task<IActionResult> EditCreditNoteTaxDetail(int creditNoteDetTaxId)
        {
            UserSessionModel userSession = SessionExtension.GetComplexData<UserSessionModel>(HttpContext.Session, "UserSession");

            ViewBag.DiscountTypeList = EnumHelper.GetEnumListFor<DiscountType>();
            ViewBag.TaxAddOrDeductList = EnumHelper.GetEnumListFor<TaxAddOrDeduct>();
            ViewBag.TaxLedgerList = await _ledger.GetLedgerSelectList((int)LedgerName.DutiesAndTaxes, userSession.CompanyId, true);

            CreditNoteDetailTaxModel creditNoteDetailTaxModel = await _creditNoteDetailTax.GetCreditNoteDetailTaxById(creditNoteDetTaxId);

            return await Task.Run(() =>
            {
                return PartialView("_AddCreditNoteTaxDetail", creditNoteDetailTaxModel);
            });
        }

        /// <summary>
        /// save credit note tax detail.
        /// </summary>
        /// <param name="creditNoteDetailTaxModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveCreditNoteTaxDetail(CreditNoteDetailTaxModel creditNoteDetailTaxModel)
        {
            JsonData<JsonStatus> data = new JsonData<JsonStatus>(new JsonStatus());

            if (ModelState.IsValid)
            {
                if (creditNoteDetailTaxModel.CreditNoteDetTaxId > 0)
                {
                    // update record.
                    if (true == await _creditNoteDetailTax.UpdateCreditNoteDetailTax(creditNoteDetailTaxModel))
                    {
                        data.Result.Status = true;
                    }
                }
                else
                {
                    // add new record.
                    if (await _creditNoteDetailTax.CreateCreditNoteDetailTax(creditNoteDetailTaxModel) > 0)
                    {
                        data.Result.Status = true;
                    }
                }
            }

            return Json(data);
        }

        /// <summary>
        /// delete creditnote tax detail.
        /// </summary>
        /// <param name="creditNoteDetTaxId"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> DeleteCreditNoteTaxDetail(int creditNoteDetTaxId)
        {
            JsonData<JsonStatus> data = new JsonData<JsonStatus>(new JsonStatus());
            if (true == await _creditNoteDetailTax.DeleteCreditNoteDetailTax(creditNoteDetTaxId))
            {
                data.Result.Status = true;
            }

            return Json(data); // returns.
        }
    }
}

ERP.UI/Areas/Accounts/Views/CreditNoteTaxDetail/_AddCreditNoteTaxDetail.cshtml
@model CreditNoteDetailTaxModel

<div class="modal-dialog modal-md">
    <div class="modal-content">
        <div class="modal-header">
            @if (Model.CreditNoteDetTaxId > 0)
            {
<h5 class="modal-title">Edit Credit Note Tax Detail</h5> }
else
{
<h5 class="modal-title">Add Credit Note Tax Detail</h5>}
        <button type="button" class="close btn-default" data-dismiss="modal" aria-label="Close">
            <i class="fas fa-times"></i>
        </button>
        </div>
        <form id="frmCreditNoteTaxDetail" class="width100" method="post"
              asp-action="SaveCreditNoteTaxDetail" asp-controller="CreditNoteTaxDetail" asp-area="Accounts"
              data-ajax-begin="return BeginCreditNoteTaxDetail();" data-ajax-success="SuccessCreditNoteTaxDetail"
              data-ajax="true" data-ajax-method="post">

            <div class="modal-body">
                @Html.HiddenFor(model => model.CreditNoteDetTaxId)
                @Html.HiddenFor(model => model.CreditNoteDetId)
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.SrNo, new { @class = "required" })
                            @Html.TextBoxFor(model => model.SrNo, new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.SrNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TaxLedgerId, new { @class = "required" })
                            @Html.DropDownListFor(model => model.TaxLedgerId, new SelectList(ViewBag.TaxLedgerList, "Value", "DisplayText"), "Select", new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.TaxLedgerId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TaxPercentageOrAmount, new { @class = "required" })
                            @Html.DropDownListFor(model => model.TaxPercentageOrAmount, new SelectList(ViewBag.DiscountTypeList, "Name", "Description"), "Select", new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.TaxPercentageOrAmount, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TaxPerOrAmountFc, new { @class = "required" })
                            @Html.TextBoxFor(model => model.TaxPerOrAmountFc, new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.TaxPerOrAmountFc, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TaxAddOrDeduct, new { @class = "required" })
                            @Html.DropDownListFor(model => model.TaxAddOrDeduct, new SelectList(ViewBag.TaxAddOrDeductList, "Name", "Description"), "Select", new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.TaxAddOrDeduct, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @*<div class="col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TaxAmountFc)
                            @Html.TextBoxFor(model => model.TaxAmountFc, new { @class = "form-control form-control-sm", @readonly = "@readonly" })
                            @Html.ValidationMessageFor(model => model.TaxAmountFc, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Remark)
                            @Html.TextBoxFor(model => model.Remark, new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal" title="Back"><i class="fas fa-arrow-left"></i> Back</button>
                <button type="submit" class="btn btn-primary" title="Save"><i class="fas fa-save"></i> Save</button>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //$('.decimal-two-scale').autoNumeric('init', { vMin: '-999999999999999.99', vMax: '999999999999999.99' });
    });

    // begin form
    function BeginCreditNoteTaxDetail() {
        var form = $("#frmCreditNoteTaxDetail");
        $(form).removeData("validator").removeData("unobtrusiveValidation");
        $.validator.unobtrusive.parse($(form));
        var validator = $(form).validate();
        var isModelValid = $(form).valid();
        if (false == isModelValid) {
            validator.focusInvalid();
            return false;
        }
    }
    // success form
    function SuccessCreditNoteTaxDetail(data) {
        if (data.Result.Status) {
            $('#modal-creditnote-detail').modal('hide');
            fnSuccessNotify('Record saved sucessfully.');
            $("#creditNoteTaxDetailGrid").DataTable().ajax.reload();
            $("#creditNoteDetailGrid").DataTable().clear().ajax.reload();
        }
        else {
            fnDangerNotify('Error occured while processing request.');
            return false;
        }
    }
</script>

ERP.UI/Areas/Accounts/Views/CreditNoteTaxDetail/_ConfirmDeleteCreditNoteTaxDetail.cshtml
<div class="modal fade" id="modalConfirmCreditNoteTaxDetail" role="dialog" data-backdrop="static" data-keyboard="true" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirm Delete</h5>
                <button type="button" class="close btn-default" data-dismiss="modal" aria-label="Close">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" title="Back"><i class="fas fa-arrow-left"></i> Back</button>
                <button type="button" class="btn btn-danger" id="delete-creditnote-tax-detail" title="Delete"><i class="fas fa-trash-alt"></i> Delete</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    // remove element button click.
    var _creditNoteDetTaxId = null;
    function fnDeleteCreditNoteTaxDetail(element, creditNoteDetTaxId) {
        _creditNoteDetTaxId = creditNoteDetTaxId;
        $(element).attr("data-target", "#modalConfirmCreditNoteTaxDetail");

        $('#modalConfirmCreditNoteTaxDetail').on('show.bs.modal', function (e) {
            // Pass form reference to modal for submission on yes/ok
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modal-footer #modalConfirmCreditNoteTaxDetail').data('form', form);
        });
    }

    // form confirm (yes/ok) handler, submits form
    $('#modalConfirmCreditNoteTaxDetail').find('.modal-footer #delete-creditnote-tax-detail').on('click', function () {
        var model = { creditNoteDetTaxId: _creditNoteDetTaxId };
        AjaxCommunication.CreateRequest(this.window, 'Post', '@Url.Action("DeleteCreditNoteTaxDetail", "CreditNoteTaxDetail")', '', model,
        function (data) {
            if (data.Result.Status) {
                $('#modalConfirmCreditNoteTaxDetail').modal('hide');
                $('#creditNoteTaxDetailGrid').DataTable().ajax.reload();
                $("#creditNoteDetailGrid").DataTable().clear().ajax.reload();
                fnSuccessNotify('Record deleted.');
            }
            else {
                fnDangerNotify('Error occured while processing request.');
            }
        }, 
        function (XMLHttpRequest, textStatus, errorThrown) {
            errorCallback(XMLHttpRequest, textStatus, errorThrown);
        }, true, null, false);
    });

</script>

ERP.UI/Areas/Accounts/Views/CreditNoteTaxDetail/_CreditNoteTaxDetail.cshtml
<div class="modal-dialog modal-xl">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Credit Note Tax Detail</h5>
            <button type="button" class="close btn-default" data-dismiss="modal" aria-label="Close">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-sm-12">
                    <table id="creditNoteTaxDetailGrid" class="table table-bordered table-striped w-100">
                        <thead>
                            <tr class="table-header">
                                <th class="no-sort">
                                    <button class="btn btn-primary mr-1 pr-1 pl-1 pb-0 pt-0" type="button" id="add-new-creditnote-taxdetl" title="Add New Line">
                                        <i class="fas fa-plus"></i>
                                    </button>

                                </th>
                                <th>CreditNoteDetTaxId</th>
                                <th>CreditNoteDetId</th>
                                <th>Sr No</th>
                                <th>Tax Ledger</th>
                                <th>Per / Amount</th>
                                <th>Tax Per Or Amount FC</th>
                                <th>Add or Deduct</th>
                                <th>Tax Amount FC</th>
                                <th>Remark</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#creditNoteTaxDetailGrid").DataTable({
            "pageLength": 25,
            "paging": false,
            "searching": false,
            "info": false,
            "dom": "<'row'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row'<'col-sm-12'tr>>" +
                "<'row'<'col-sm-4'i><'col-sm-4 text-center'><'col-sm-4'p>>",
            "bPaginate": true,
            "scrollX": true,
            "ajax": {
                "url": "@Url.Action("GetCreditNoteTaxDetailList", "CreditNoteTaxDetail", new { CreditNoteDetId = ViewBag.CreditNoteDetId })",
                "type": "POST",
                "datatype": "json",
            },
            "columns": [
                {
                    "orderable": false,
                    "render": function (data, type, full, meta) {
                        return '<div class="action_button">' +
                            '<button type="button" class="border-0 rounded-0 text-success" title="Edit" onclick="javascript: fnEditCreditNoteTaxDetail(' + full.CreditNoteDetTaxId + ')"><i class="far fa-edit"></i></button>' +
                            '<button type="button" class="border-0 rounded-0 text-danger" title="Delete" data-toggle="modal" onclick="javascript: fnDeleteCreditNoteTaxDetail(this, ' + full.CreditNoteDetTaxId + ')"><i class="fa fa-trash-alt"></i></button>' +
                            '</div>';
                    }
                },
                { "data": "CreditNoteDetTaxId", "name": "CreditNoteDetTaxId", "visible": false },
                { "data": "CreditNoteDetId", "name": "CreditNoteDetId", "visible": false },
                { "data": "SrNo", "name": "SrNo" },
                { "data": "TaxLedgerName", "name": "TaxLedgerName" },
                { "data": "TaxPercentageOrAmount", "name": "TaxPercentageOrAmount" },
                { "data": "TaxPerOrAmountFc", "name": "TaxPerOrAmountFc", render: $.fn.dataTable.render.number(',', '.', 2, '') },
                { "data": "TaxAddOrDeduct", "name": "TaxAddOrDeduct" },
                { "data": "TaxAmountFc", "name": "TaxAmountFc", render: $.fn.dataTable.render.number(',', '.', 2, '')},
                { "data": "Remark", "name": "Remark" }
            ],
        });
    });

    // add creditnote tax detail.
    $('#add-new-creditnote-taxdetl').click(function () {
        var model = { creditNoteDetId: '@ViewBag.CreditNoteDetId' };
        AjaxCommunication.CreateRequest(this.window, 'Get', '@Url.Action("AddCreditNoteTaxDetail", "CreditNoteTaxDetail")', 'html', model,
        function (data) {
            $('#modal-creditnote-detail').empty();
            $('#modal-creditnote-detail').html(data).modal('show');
            return false;
        }, 
        function (XMLHttpRequest, textStatus, errorThrown) {
            errorCallback(XMLHttpRequest, textStatus, errorThrown);
        }, true, null, false);
    });

     // edit creditnote tax detail.
    function fnEditCreditNoteTaxDetail(creditNoteDetTaxId) {
        var model = { creditNoteDetTaxId: creditNoteDetTaxId };
        AjaxCommunication.CreateRequest(this.window, 'Get', '@Url.Action("EditCreditNoteTaxDetail", "CreditNoteTaxDetail")', 'html', model,
        function (data) {
            $('#modal-creditnote-detail').empty();
            $('#modal-creditnote-detail').html(data).modal('show');
            return false;
        }, 
        function (XMLHttpRequest, textStatus, errorThrown) {
            errorCallback(XMLHttpRequest, textStatus, errorThrown);
        }, true, null, false);
    }
</script>
@{ await Html.RenderPartialAsync("_ConfirmDeleteCreditNoteTaxDetail"); }
<style>
    /*#modal-creditnote .modal-dialog {
        height: 90%;*/ /* = 90% of the .modal-backdrop block = %90 of the screen */
    /*}

    #modal-creditnote .modal-content {
        height: 100%;*/ /* = 100% of the .modal-dialog block */
    /*}

    #modal-creditnote .modal-body {
        height: 300px;
        overflow-y: auto;
    }

    @@media (min-height: 500px) {
        #modal-creditnote .modal-body {
            height: 400px;
        }
    }

    @@media (min-height: 800px) {
        #modal-creditnote .modal-body {
            height: 600px;
        }
    }*/
</style>