ERP.UI/Areas/Accounts/Controllers/CurrencyController.cs
using ERP.Models.Common;
using ERP.Models.Helpers;
using ERP.Models.Accounts;
using ERP.Services.Accounts.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ERP.UI.Areas.Accounts.Controllers
{
    [Area("Accounts")]
    public class CurrencyController : Controller
    {
        private readonly ICurrency _currency;

        /// <summary>
        /// constractor.
        /// </summary>
        /// <param name="currency"></param>
        public CurrencyController(ICurrency currency)
        {
            this._currency = currency;
        }

        /// <summary>
        /// currency list.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return await Task.Run(() =>
            {
                return View();
            });
        }

        /// <summary>
        /// get currency list.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> GetCurrencyList()
        {
            DataTableResultModel<CurrencyModel> resultModel = await _currency.GetCurrencyList();

            return await Task.Run(() =>
            {
                return Json(new { draw = 1, data = resultModel.ResultList });
            });
        }

        /// <summary>
        /// add new currency.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<PartialViewResult> AddCurrency()
        {
            return await Task.Run(() =>
            {
                return PartialView("_AddCurrency", new CurrencyModel());
            });
        }

        /// <summary>
        /// edit currency.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<PartialViewResult> EditCurrency(int currencyId)
        {
            CurrencyModel currencyModel = await _currency.GetCurrencyById(currencyId);

            return PartialView("_AddCurrency", currencyModel);
        }

        /// <summary>
        /// save currency.
        /// </summary>
        /// <param name="currencyModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveCurrency(CurrencyModel currencyModel)
        {

            JsonData<JsonStatus> data = new JsonData<JsonStatus>(new JsonStatus());

            if (ModelState.IsValid)
            {
                if (currencyModel.CurrencyId > 0)
                {
                    // update record.
                    if (true == await _currency.UpdateCurrency(currencyModel))
                    {
                        data.Result.Status = true;
                    }
                }
                else
                {
                    // add new record.
                    if (await _currency.CreateCurrency(currencyModel) > 0)
                    {
                        data.Result.Status = true;
                    }
                }
            }

            return Json(data);
        }

        

        /// <summary>
        /// delete currency by currencyid.
        /// </summary>
        /// <param name="currencyId"></param>
        /// <returns>
        /// return json.
        /// </returns>
        [HttpPost]
        public async Task<JsonResult> DeleteCurrency(int currencyId)
        {
            JsonData<JsonStatus> data = new JsonData<JsonStatus>(new JsonStatus());

            if (true == await _currency.DeleteCurrency(currencyId))
            {
                data.Result.Status = true;
            }

            return Json(data); // returns.
        }
    }
}

ERP.UI/Areas/Accounts/Views/Currency/Index.cshtml
@{
    ViewBag.Title = "Currency List";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Currency List</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <button class="btn btn-primary btn-block" type="button" id="add-new-currency">
                            <i class="fas fa-plus"></i> New
                        </button>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <table id="currencyGrid" class="table table-bordered table-striped w-100">
                            <thead>
                                <tr class="table-header">
                                    <th>Action</th>
                                    <th>Currency Name</th>
                                    <th>Currency Code</th>
                                    <th>Denomination</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
$(document).ready(function () {
    $("#currencyGrid").DataTable({

        //dom: 'lftip',
        "pageLength": 25,
        "lengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
        "bPaginate": true,
        //"bInfo": true,
        //"bRetrieve": true,
        //"bFilter": true,
        //"iDisplayLength": 5,
        //"bSort": true,
        //"aaSorting": [],
        //"order": [],
        //scrollY: "50vh",
        //scrollCollapse: true,

        "ajax": {
            "url": "@Url.Action("GetCurrencyList", "Currency")",
            "type": "POST",
            "datatype": "json",
        },
        "columns": [
            {
                "render": function (data, type, full, meta) {
                    return '<div class="action_button">' +
                        '<button type="button" class="border-0 rounded-0 text-success" onclick="javascript: fnEditCurrency(' + full.CurrencyId + ')"><i class="far fa-edit"></i></button>' +
                        '<button type="button" class="border-0 rounded-0 text-danger" data-toggle="modal" onclick="javascript: fnDeleteCurrency(this, ' + full.CurrencyId + ')"><i class="fa fa-trash-alt"></i></button>' +
                        '</div>';
                }, "orderable": false
            },
            { "data": "CurrencyName", "name": "Currency Name" },
            { "data": "CurrencyCode", "name": "Currency Code" },
            { "data": "Denomination", "name": "Denomination" }
        ],
    });
});

// add new record.
$('#add-new-currency').click(function () {
    AjaxCommunication.CreateRequest(this.window, 'Get', '@Url.Action("AddCurrency", "Currency")', 'html', '',
    function (data) {
        $('#modal-currency-master').empty();
        $('#modal-currency-master').html(data).modal('show');
        return false;
    }, 
    function (XMLHttpRequest, textStatus, errorThrown) {
            errorCallback(XMLHttpRequest, textStatus, errorThrown);
        }, true, null, false);
});

// edit currency
    function fnEditCurrency(currencyId) {
        var model = { currencyId: currencyId };
        AjaxCommunication.CreateRequest(this.window, 'Get', '@Url.Action("EditCurrency", "Currency")', 'html', model,
        function (data) {
            $('#modal-currency-master').empty();
            $('#modal-currency-master').html(data).modal('show');
            return false;
        }, 
        function (XMLHttpRequest, textStatus, errorThrown) {
            errorCallback(XMLHttpRequest, textStatus, errorThrown);
        }, true, null, false);
    }
</script>

@{ await Html.RenderPartialAsync("_ConfirmDeleteCurrency"); }

<div id="modal-currency-master" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="true"></div>

ERP.UI/Areas/Accounts/Views/Currency/_AddCurrency.cshtml
@model CurrencyModel

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            @if (Model.CurrencyId > 0)
            {
                <h4 class="modal-title">Edit Currency</h4>
            }
            else
            {
                <h4 class="modal-title">Add Currency</h4>
            }
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-header-close" aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="frmSaveCurrency" class="width100" method="post"
              asp-action="SaveCurrency" asp-controller="Currency" asp-area="Accounts"
              data-ajax-begin="return BeginSaveCurrency();" data-ajax-success="SuccessSaveCurrency"
              data-ajax="true" data-ajax-method="post">

            <div class="modal-body">
                @Html.HiddenFor(model => model.CurrencyId)

                <div class="form-group">
                    @Html.LabelFor(model => model.CurrencyName, new { @class = "required" })
                    @Html.TextBoxFor(model => model.CurrencyName, new { @class = "form-control", @maxlength = "100" })
                    @Html.ValidationMessageFor(model => model.CurrencyName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CurrencyCode, new { @class = "required" })
                    @Html.TextBoxFor(model => model.CurrencyCode, new { @class = "form-control", @maxlength = "100" })
                    @Html.ValidationMessageFor(model => model.CurrencyCode)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Denomination, new { @class = "required" })
                    @Html.TextBoxFor(model => model.Denomination, new { @class = "form-control", @maxlength = "100" })
                    @Html.ValidationMessageFor(model => model.Denomination)
                </div>

            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" title="Cancel">Cancel</button>
                <button type="submit" class="btn btn-primary" title="Submit">Save</button>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
   
    // begin form
    function BeginSaveCurrency() {
        var form = $("#frmSaveCurrency");
        $(form).removeData("validator").removeData("unobtrusiveValidation");
        $.validator.unobtrusive.parse($(form));
        var validator = $(form).validate();
        var isModelValid = $(form).valid();
        if (false == isModelValid) {
            validator.focusInvalid();
            return false;
        }
    }
    // success form
    function SuccessSaveCurrency(data) {
        if (data.Result.Status) {
            $('#modal-currency-master').modal('hide');
            fnSuccessNotify('Record saved sucessfully.');
            $('#currencyGrid').DataTable().ajax.reload();
        }
        else
        {
            fnDangerNotify('Error occured while processing request.');
            return false;
        }
    }
</script>

ERP.UI/Areas/Accounts/Views/Currency/_ConfirmDeleteCurrency.cshtml
<div class="modal fade" id="modalConfirmDeleteCurrency" role="dialog" data-backdrop="static" data-keyboard="true" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-title classh4">Confirm Delete</div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span class="modal-header-close" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete?</p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn-delete-currency">Delete</button>
            </div>
        </div>
    </div>
</div>

<script>
    // remove element button click.
    var _currencyId = null;
    function fnDeleteCurrency(element, currencyId) {
        _currencyId = currencyId;
        $(element).attr("data-target", "#modalConfirmDeleteCurrency");

        $('#modalConfirmDeleteCurrency').on('show.bs.modal', function (e) {
            // Pass form reference to modal for submission on yes/ok
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modal-footer #modalConfirmDeleteCurrency').data('form', form);
        });
    }

    // form confirm (yes/ok) handler, submits form
    $('#modalConfirmDeleteCurrency').find('.modal-footer #btn-delete-currency').on('click', function () {
        var model = { currencyId: _currencyId };
        AjaxCommunication.CreateRequest(this.window, 'Post', '@Url.Action("DeleteCurrency", "Currency")', '', model,
        function (data) {
            if (data.Result.Status) {
                $('#modalConfirmDeleteCurrency').modal('hide');
                $('#currencyGrid').DataTable().ajax.reload();
                fnSuccessNotify('Record deleted.');
            }
            else {
                fnDangerNotify('Error occured while processing request.');
            }
        }, 
        function (XMLHttpRequest, textStatus, errorThrown) {
            errorCallback(XMLHttpRequest, textStatus, errorThrown);
        }, true, null, false);
    });

</script>